language: go

sudo: false

go:
  - 1.10
  - 1.11
  - 1.12
  - 1.13
  - tip

before_install:
  - |
    curl -L https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-`uname -s`-`uname -m`>/tmp/docker-machine &&
    sudo mv /tmp/docker-machine /usr/local/bin/docker-machine &&
    chmod +x /usr/local/bin/docker-machine

install:
  - go install

script: docker-machine create -d scaleway -h | grep "scaleway"
